<?php

require_once(get_template_directory() . '/includes/acf/torque-acf-search-class.php');

class Atlantic_Residential_ACF
{

  public function __construct()
  {
    add_action('admin_init', array($this, 'acf_admin_init'), 99);
    add_action('acf/init', array($this, 'acf_init'));

    // hide acf in admin - client doesnt need to see this
    // add_filter('acf/settings/show_admin', '__return_false');

    // add acf fields to wp search
    if (class_exists('Torque_ACF_Search')) {
      add_filter(Torque_ACF_Search::$ACF_SEARCHABLE_FIELDS_FILTER_HANDLE, array($this, 'add_fields_to_search'));
    }
  }

  public function acf_admin_init()
  {
    // hide options page
    // remove_menu_page('acf-options');
  }

  public function add_fields_to_search($fields)
  {
    // $fields[] = 'custom_field_name';
    $fields[] = 'city';
    $fields[] = 'state';
    $fields[] = 'street_address';
    return $fields;
  }

  public function acf_init()
  {
    /**
     * 20190812: CURRENTLY IMPLEMENTED USING THE JSON DEFINITIONS (/acf-json/)
     */
    /* if( function_exists('acf_add_local_field_group') ):

      acf_add_local_field_group(array(
        'key' => 'group_5d23b5d75e7ee',
        'title' => 'Careers Modules',
        'fields' => array(
          array(
            'key' => 'field_5d23bcb87dccc',
            'label' => 'Career Modules',
            'name' => 'career_modules',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layouts' => array(
              '5c9561c74csdc34' => array(
                'key' => '5c9561c74csdc34',
                'name' => 'content_section_one',
                'label' => 'Content Section (Image & Text)',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5c9563c44bzz2',
                    'label' => 'Align Text',
                    'name' => 'align',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'left' => 'Left',
                      'right' => 'Right',
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'default_value' => 'left',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                    'save_other_choice' => 0,
                  ),
                  array(
                    'key' => 'field_5c95m29e91af35',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                  array(
                    'key' => 'field_5c23b7c1af36',
                    'label' => 'Heading',
                    'name' => 'heading',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_5c95627v4af37',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'default_value' => '',
                    'delay' => 0,
                  ),
                  array(
                    'key' => 'field_5c956282xcr4',
                    'label' => 'CTA',
                    'name' => 'cta',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                  array(
                    'key' => 'field_5db4xsc15512',
                    'label' => 'Top/Bottom Padding?',
                    'name' => 'top_bottom_padding',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'yes' => 'Yes',
                      'no' => 'No',
                    ),
                    'default_value' => array(
                      0 => 'yes',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5d23c62e9f0d4' => array(
                'key' => 'layout_5d23c62e9f0d4',
                'name' => 'list_careers_simple',
                'label' => 'List Careers (simple)',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5d23c643vswd5',
                    'label' => 'Number of Careers',
                    'name' => 'number_of_careers',
                    'type' => 'select',
                    'instructions' => 'How many careers to show initially, and upon every click of \'load more\'.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      999 => 'All',
                      1 => '1',
                      2 => '2',
                      3 => '3',
                      4 => '4',
                      5 => '5',
                      6 => '6',
                      7 => '7',
                      8 => '8',
                      9 => '9',
                      10 => '10',
                    ),
                    'default_value' => array(
                      0 => '999',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5d23c6b79f0d6' => array(
                'key' => 'layout_5d23c6b79f0d6',
                'name' => 'careers_form',
                'label' => 'Careers Form',
                'display' => 'block',
                'sub_fields' => array(
                ),
                'min' => '',
                'max' => '',
              ),
            ),
            'button_label' => 'Add Careers Module',
            'min' => '',
            'max' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'page_template',
              'operator' => '==',
              'value' => 'careers.php',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5c953fd028818',
        'title' => 'Company Details',
        'fields' => array(
          array(
            'key' => 'field_5c953fd49ef57',
            'label' => 'Address',
            'name' => 'address',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_5c953fe99ef58',
            'label' => 'Phone',
            'name' => 'phone',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5c953fff9ef59',
            'label' => 'Fax',
            'name' => 'fax',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5c953fff9ef22',
            'label' => 'Email',
            'name' => 'email',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5c9540109ef5a',
            'label' => 'Copyright',
            'name' => 'copyright',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'options_page',
              'operator' => '==',
              'value' => 'acf-options',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
        'modified' => false,
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5di2hdxbd75e7ee',
        'title' => 'Contact Modules',
        'fields' => array(
          array(
            'key' => 'field_5c95378kasdf7a',
            'label' => 'Intro',
            'name' => 'page_intro',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_5d4b4f97103ec',
            'label' => 'Map ID',
            'name' => 'map_id',
            'type' => 'number',
            'instructions' => 'The Map ID (number only) from the Map shortcode, e.g: 1025',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'page_template',
              'operator' => '==',
              'value' => 'contact.php',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5d17d7b1829b6',
        'title' => 'Header Style',
        'fields' => array(
          array(
            'key' => 'field_5d17d7f1eb04a',
            'label' => 'Light or Dark?',
            'name' => 'light_or_dark_header',
            'type' => 'select',
            'instructions' => 'Select light for darkly colored backgrounds, and dark for lightly colored backgrounds',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'light' => 'Light Header',
              'dark' => 'Dark Header',
            ),
            'default_value' => array(
              0 => 'dark',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
            array(
              'param' => 'post_template',
              'operator' => '!=',
              'value' => 'listings.php',
            ),
          ),
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'torque_listing',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
        'modified' => false,
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5c954a9073a65',
        'title' => 'Page Hero',
        'fields' => array(
          array(
            'key' => 'field_5c954a9886085',
            'label' => 'Type',
            'name' => 'hero_type',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'none' => 'None',
              'image' => 'Image',
              'image_slideshow' => 'Image Slideshow',
              'video' => 'Video',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => array(
              0 => 'image',
            ),
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5c954ac486086',
            'label' => 'Image',
            'name' => 'hero_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c954a9886085',
                  'operator' => '==',
                  'value' => 'image',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5c954ae486087',
            'label' => 'Image Slideshow',
            'name' => 'hero_image_slideshow',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c954a9886085',
                  'operator' => '==',
                  'value' => 'image_slideshow',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'torque_slideshow',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
          ),
          array(
            'key' => 'field_5c954e7f5e0fc',
            'label' => 'Video Src',
            'name' => 'hero_video_src',
            'type' => 'file',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c954a9886085',
                  'operator' => '==',
                  'value' => 'video',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'return_format' => 'url',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'library' => 'all',
            'min_size' => 0,
            'max_size' => 0,
            'mime_types' => '',
          ),
          array(
            'key' => 'field_3c568c452lak',
            'label' => 'Positioning',
            'name' => 'hero_positioning',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c954a9886085',
                  'operator' => '!=',
                  'value' => 'none',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'top' => 'Top of the viewport',
              'after' => 'After the header bar',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => array(
              0 => 'top',
            ),
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
          ),
          array(
            'key' => 'field_3cnnad2k29d2lak',
            'label' => 'Hero Height',
            'name' => 'hero_height',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c954a9886085',
                  'operator' => '!=',
                  'value' => 'none',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'full' => 'Full-height',
              'half' => 'Half-height',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => array(
              0 => 'full',
            ),
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5c568c9903dfjx',
            'label' => 'Text Alignment',
            'name' => 'hero_alignment',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c954a9886085',
                  'operator' => '!=',
                  'value' => 'none',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'none' => 'None',
              'left' => 'Left Aligned',
              'center' => 'Center Aligned',
              'right' => 'Right Aligned',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => array(
              0 => 'none',
            ),
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5c954bb12e42b',
            'label' => 'Overlay Title',
            'name' => 'hero_overlay_title',
            'type' => 'text',
            'instructions' => 'use em tags to emphasise certain words',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c954a9886085',
                  'operator' => '!=',
                  'value' => 'none',
                ),
                array(
                  'field' => 'field_5c568c9903dfjx',
                  'operator' => '!=',
                  'value' => 'none',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'eg <em>Emphasised text</em> in title',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5c954be22e42c',
            'label' => 'Overlay Subtitle',
            'name' => 'hero_overlay_subtitle',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c954a9886085',
                  'operator' => '!=',
                  'value' => 'none',
                ),
                array(
                  'field' => 'field_5c568c9903dfjx',
                  'operator' => '!=',
                  'value' => 'none',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
            array(
              'param' => 'post_template',
              'operator' => '==',
              'value' => 'default',
            ),
          ),
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
            array(
              'param' => 'post_template',
              'operator' => '==',
              'value' => 'contact.php',
            ),
          ),
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
            array(
              'param' => 'post_template',
              'operator' => '==',
              'value' => 'careers.php',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5d25f91dd25d6',
        'title' => 'Properties Modules',
        'fields' => array(
          array(
            'key' => 'field_5d4b61384347c',
            'label' => 'Tagline',
            'name' => 'tagline',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5d25f95748ff0',
            'label' => 'Heading',
            'name' => 'heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5d25f98548ff1',
            'label' => 'Intro',
            'name' => 'intro',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_5d4cc147cea52',
            'label' => 'CTA Heading',
            'name' => 'cta_heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5d4cc198cea53',
            'label' => 'CTA Content',
            'name' => 'cta_content',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => '',
          ),
          array(
            'key' => 'field_5d4cc1a1cea54',
            'label' => 'CTA Link',
            'name' => 'cta_link',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
          array(
            'key' => 'field_5d4cc1c5cea55',
            'label' => 'CTA Align Background Graphic',
            'name' => 'cta_align_background_graphic',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'left' => 'Left',
              'right' => 'Right',
            ),
            'default_value' => array(
              0 => 'right',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
            array(
              'param' => 'post_template',
              'operator' => '==',
              'value' => 'listings.php',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5d263be30e5aa',
        'title' => 'Property Modules',
        'fields' => array(
          array(
            'key' => 'field_5d2648f5cd0e7',
            'label' => 'Logo',
            'name' => 'logo',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'full',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5d4cd7b0232e3',
            'label' => 'Street Address',
            'name' => 'street_address',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5d4cd7f5232e4',
            'label' => 'City',
            'name' => 'city',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5d4cd7fc232e5',
            'label' => 'State',
            'name' => 'state',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5d26495acd0e9',
            'label' => 'Key Details',
            'name' => 'key_details',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
              array(
                'key' => 'field_5d264964cd0ea',
                'label' => 'Key',
                'name' => 'key',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_5d264987cd0eb',
                'label' => 'Value',
                'name' => 'value',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
          ),
          array(
            'key' => 'field_5d26499fcd0ec',
            'label' => 'Property CTA',
            'name' => 'cta',
            'type' => 'link',
            'instructions' => 'Link to property website, etc...',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'torque_listing',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5ce3438132e73',
        'title' => 'Social Media',
        'fields' => array(
          array(
            'key' => 'field_5ce34402d4dab',
            'label' => 'Social Media',
            'name' => 'social_media',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
              array(
                'key' => 'field_5ce34426d4dac',
                'label' => 'Social Channel',
                'name' => 'social_channel',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'twitter' => 'Twitter',
                  'linkedin' => 'LinkedIn',
                  'instagram' => 'Instagram',
                  'facebook' => 'Facebook',
                  'youtube' => 'YouTube',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5ce34444d4dad',
                'label' => 'Social URL',
                'name' => 'social_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
            ),
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'options_page',
              'operator' => '==',
              'value' => 'acf-options',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
        'modified' => false,
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5cd44dac63578',
        'title' => 'Staff Details',
        'fields' => array(
          array(
            'key' => 'field_5cd44dd099191',
            'label' => 'Job Titles',
            'name' => 'staff_job_titles',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add a Job Title',
            'sub_fields' => array(
              array(
                'key' => 'field_5cd44e82fd6d5',
                'label' => 'Job Title',
                'name' => 'staff_job_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'options_page',
              'operator' => '==',
              'value' => 'acf-options',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
        'modified' => false,
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5c955c2570f80',
        'title' => 'Page Intro',
        'fields' => array(
          array(
            'key' => 'field_5c955c931df7b',
            'label' => 'Text Alignment',
            'name' => 'page_intro_alignment',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'none' => 'None',
              'left' => 'Left Aligned',
              'center' => 'Center Aligned',
              'right' => 'Right Aligned',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => array(
              0 => 'center',
            ),
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5c945c456df9e',
            'label' => 'Color Combination (Background/Text)',
            'name' => 'page_intro_color',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'color1' => 'Blue-gray/White',
              'color2' => 'Blue-gray/Medium Green',
              'color3' => 'Blue-gray/Light Green',
              'color4' => 'Medium Green/White',
              'color5' => 'Medium Green/Blue-gray',
              'color6' => 'Medium Green/Light Green',
              'color7' => 'Light Green/White',
              'color8' => 'Light Green/Blue-gray',
              'color9' => 'Light Green/Medium Green',
              'color10' => 'White/Blue-gray',
              'color11' => 'White/Medium Green',
              'color12' => 'White/Light Green',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => array(
              0 => 'color4',
            ),
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5c955c421df79',
            'label' => 'Heading',
            'name' => 'page_heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c955c931df7b',
                  'operator' => '!=',
                  'value' => 'none',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5c955c581df7a',
            'label' => 'Intro',
            'name' => 'page_intro',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5c955c931df7b',
                  'operator' => '!=',
                  'value' => 'none',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_5d41c394f36e1',
            'label' => 'CTA',
            'name' => 'cta',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
            array(
              'param' => 'post_template',
              'operator' => '==',
              'value' => 'default',
            ),
          ),
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
            array(
              'param' => 'post_template',
              'operator' => '==',
              'value' => 'careers.php',
            ),
          ),
        ),
        'menu_order' => 2,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5c9519163d799',
        'title' => 'Content Modules',
        'fields' => array(
          array(
            'key' => 'field_5c951924e250c',
            'label' => 'Modules',
            'name' => 'modules',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layouts' => array(
              '5c9561c747434' => array(
                'key' => '5c9561c747434',
                'name' => 'content_section_one',
                'label' => 'Content Section (Image & Text)',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5c9563c44bc13',
                    'label' => 'Align Text',
                    'name' => 'align',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'left' => 'Left',
                      'right' => 'Right',
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'default_value' => 'left',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                    'save_other_choice' => 0,
                  ),
                  array(
                    'key' => 'field_5c9561e91af35',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                  array(
                    'key' => 'field_5d41deaf41ea1',
                    'label' => 'Image Background Size',
                    'name' => 'image_background_size',
                    'type' => 'select',
                    'instructions' => 'Depending on the type of CTA, you can ensure the image covers the entire image section, is contained within, or retains the dimensions as uploaded.',
                    'required' => 0,
                    'conditional_logic' => array(
                      array(
                        array(
                          'field' => 'field_5c9561e91af35',
                          'operator' => '!=empty',
                        ),
                      ),
                    ),
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'cover' => 'Cover',
                      'auto' => 'Auto',
                      'contain' => 'Contain',
                    ),
                    'default_value' => array(
                      0 => 'cover',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5c95621c1af36',
                    'label' => 'Heading',
                    'name' => 'heading',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_5c9562761af37',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 5,
                    'new_lines' => 'br',
                  ),
                  array(
                    'key' => 'field_5c9562871af38',
                    'label' => 'CTA',
                    'name' => 'cta',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                  array(
                    'key' => 'field_5d239831fd912',
                    'label' => 'Top/Bottom Padding?',
                    'name' => 'top_bottom_padding',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'yes' => 'Yes',
                      'no' => 'No',
                    ),
                    'default_value' => array(
                      0 => 'yes',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5d41e1587b27c',
                    'label' => 'Reduced Height?',
                    'name' => 'reduced_height',
                    'type' => 'select',
                    'instructions' => 'Reduces the height by almost half, used in conjunction with smaller images & Image Background Size: Auto.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'no' => 'No',
                      'yes' => 'Yes',
                    ),
                    'default_value' => array(
                      0 => 'no',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5d1ce56d29a77' => array(
                'key' => 'layout_5d1ce56d29a77',
                'name' => 'content_section_two',
                'label' => 'Content Section (Heading & Text)',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5d1ce5f229a79',
                    'label' => 'Color Combination (Background/Text)',
                    'name' => 'color_combo',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'color1' => 'Blue-gray/White',
                      'color2' => 'Blue-gray/Medium Green',
                      'color3' => 'Blue-gray/Light Green',
                      'color4' => 'Medium Green/White',
                      'color5' => 'Medium Green/Blue-gray',
                      'color6' => 'Medium Green/Light Green',
                      'color7' => 'Light Green/White',
                      'color8' => 'Light Green/Blue-gray',
                      'color9' => 'Light Green/Medium Green',
                      'color10' => 'White/Blue-gray',
                      'color11' => 'White/Medium Green',
                      'color12' => 'White/Light Green',
                      'color13' => 'Gray/Blue-gray',
                      'color14' => 'Gray/Medium Green',
                      'color15' => 'Gray/Light Green',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5d1ce5bc29a78',
                    'label' => 'Align Text',
                    'name' => 'align',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'left' => 'Left Aligned',
                      'center' => 'Center Aligned',
                      'right' => 'Right Aligned',
                    ),
                    'default_value' => array(
                      0 => 'center',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5d1ce74c29a7a',
                    'label' => 'Heading',
                    'name' => 'heading',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_5d1ce76029a7b',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                  ),
                  array(
                    'key' => 'field_5d1ce523jkb29a78',
                    'label' => 'Bottom Padding?',
                    'name' => 'bottom_padding',
                    'type' => 'select',
                    'instructions' => 'Yes: identical bottom-padding to Page Intro section. No: minimal bottom-padding, for use in conjunction with introducing another Module for instance.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'yes' => 'Yes',
                      'no' => 'No',
                    ),
                    'default_value' => array(
                      0 => 'yes',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5c99241c74csl36' => array(
                'key' => 'layout_5c99241c74csl36',
                'name' => 'content_section_three',
                'label' => 'Content Section (Image, Quote & Full-width CTA)',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_xo23jf349csd',
                    'label' => 'Align Text',
                    'name' => 'align',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'left' => 'Left',
                      'right' => 'Right',
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'default_value' => 'left',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                    'save_other_choice' => 0,
                  ),
                  array(
                    'key' => 'field_xo23jfk8nb76d',
                    'label' => 'Background Color',
                    'name' => 'background_color',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'white' => 'White',
                      'green' => 'Green',
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'default_value' => array(
                      0 => 'white',
                    ),
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                    'save_other_choice' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_mmj2d20disfc',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                  array(
                    'key' => 'field_5kjh23xsaf',
                    'label' => 'Quote',
                    'name' => 'quote',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_1lksc76029a7b',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                  ),
                  array(
                    'key' => 'field_5c2dsihbbqw',
                    'label' => 'CTA',
                    'name' => 'cta',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5c956991bcc4b' => array(
                'key' => 'layout_5c956991bcc4b',
                'name' => 'cta_section',
                'label' => 'CTA Section',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5c956991bcc4c',
                    'label' => 'Heading',
                    'name' => 'heading',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_5c956991bcc4d',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 5,
                    'new_lines' => 'br',
                  ),
                  array(
                    'key' => 'field_5c956991bcc4e',
                    'label' => 'CTA',
                    'name' => 'cta',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                  array(
                    'key' => 'field_5d239c82b5ee1',
                    'label' => 'Align Background Graphic',
                    'name' => 'align_background_graphic',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'left' => 'Left',
                      'right' => 'Right',
                    ),
                    'default_value' => array(
                      0 => 'right',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5d238fd521011' => array(
                'key' => 'layout_5d238fd521011',
                'name' => 'image_gallery',
                'label' => 'Image Gallery (Simple)',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5d238fdd21012',
                    'label' => 'Images',
                    'name' => 'images',
                    'type' => 'gallery',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'min' => 1,
                    'max' => 20,
                    'insert' => 'append',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5c869eb43ec10' => array(
                'key' => 'layout_5c869eb43ec10',
                'name' => 'gallery_grid',
                'label' => 'Gallery Grid (Complex)',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5c869ee83ec12',
                    'label' => 'Grid Rows',
                    'name' => 'grid_rows',
                    'type' => 'range',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 1,
                    'min' => 1,
                    'max' => 2,
                    'step' => 1,
                    'prepend' => '',
                    'append' => '',
                  ),
                  array(
                    'key' => 'field_5c869fef3ec13',
                    'label' => 'Images',
                    'name' => 'images',
                    'type' => 'repeater',
                    'instructions' => 'Picture a grid with 12 columns and 2 rows. </br>The grid lines between the columns (including the first and last one) can be labelled from 0 to 13, and between the rows from 0 to 2. </br>For each image, you can define the area in this grid that it will live in (on desktop) by giving it a column line start/finish and a row line start/finish. </br></br> The order you add the images will have no effect on desktop (since we\'re just giving it a grid area), but will be relevant for mobile and tablet.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'collapsed' => 'field_5c869ffc3ec14',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Image',
                    'sub_fields' => array(
                      array(
                        'key' => 'field_5c869ffc3ec14',
                        'label' => 'Image',
                        'name' => 'image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '',
                          'class' => '',
                          'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                      ),
                      array(
                        'key' => 'field_5c86a00f3ec15',
                        'label' => 'Column Start',
                        'name' => 'column_start',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 0,
                        'max' => 11,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                      ),
                      array(
                        'key' => 'field_5c86a0573ec16',
                        'label' => 'Column End',
                        'name' => 'column_end',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 1,
                        'max' => 12,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                      ),
                      array(
                        'key' => 'field_5c86a0693ec17',
                        'label' => 'Row Start',
                        'name' => 'row_start',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 0,
                        'max' => 1,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                      ),
                      array(
                        'key' => 'field_5c86a07f3ec18',
                        'label' => 'Row End',
                        'name' => 'row_end',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 1,
                        'max' => 2,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                      ),
                    ),
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5d2393bd98f24' => array(
                'key' => 'layout_5d2393bd98f24',
                'name' => 'video',
                'label' => 'Video',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5d23940098f25',
                    'label' => 'Video',
                    'name' => 'video_src',
                    'type' => 'file',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'url',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => 50,
                    'mime_types' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              '5c95192ad0ff0' => array(
                'key' => '5c95192ad0ff0',
                'name' => 'post_slideshow',
                'label' => 'Post Slideshow',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5c951939e250d',
                    'label' => 'Slideshow',
                    'name' => 'slideshow_id',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'post_type' => array(
                      0 => 'torque_post_ss',
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              '5c9d3f4702dde' => array(
                'key' => '5c9d3f4702dde',
                'name' => 'staff_members',
                'label' => 'Staff Members',
                'display' => 'block',
                'sub_fields' => array(
                ),
                'min' => '',
                'max' => '',
              ),
              '5c9d3f4702arg' => array(
                'key' => '5c9d3f4702arg',
                'name' => 'mailchimp_form',
                'label' => 'MailChimp Form',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5c951939e2222',
                    'label' => 'Title',
                    'name' => 'mailchimp_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'post_type' => array(
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => '',
                    'ui' => 1,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                  ),
                  array(
                    'key' => 'field_5c951939e2332',
                    'label' => 'description',
                    'name' => 'mailchimp_desc',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'post_type' => array(
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => '',
                    'ui' => 1,
                    'default_value' => '',
                    'new_lines' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'rows' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
            ),
            'button_label' => 'Add Module',
            'min' => '',
            'max' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
            array(
              'param' => 'post_template',
              'operator' => '==',
              'value' => 'default',
            ),
            array(
              'param' => 'post_template',
              'operator' => '!=',
              'value' => 'careers.php',
            ),
            array(
              'param' => 'post_template',
              'operator' => '!=',
              'value' => 'contact.php',
            ),
          ),
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'torque_listing',
            ),
          ),
        ),
        'menu_order' => 10,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
        'modified' => false,
      ));
      
    endif; */
  }
}
