<?php

require_once(get_template_directory() . '/includes/acf/torque-acf-search-class.php');

class Atlantic_Residential_ACF
{

  public function __construct()
  {
    add_action('admin_init', array($this, 'acf_admin_init'), 99);
    add_action('acf/init', array($this, 'acf_init'));

    // hide acf in admin - client doesnt need to see this
    // add_filter('acf/settings/show_admin', '__return_false');

    // add acf fields to wp search
    if (class_exists('Torque_ACF_Search')) {
      add_filter(Torque_ACF_Search::$ACF_SEARCHABLE_FIELDS_FILTER_HANDLE, array($this, 'add_fields_to_search'));
    }
  }

  public function acf_admin_init()
  {
    // hide options page
    // remove_menu_page('acf-options');
  }

  public function add_fields_to_search($fields)
  {
    // $fields[] = 'custom_field_name';
    return $fields;
  }

  public function acf_init()
  {

    acf_add_local_field_group(array(
      'key' => 'group_5c953fd028818',
      'title' => 'Company Details',
      'fields' => array(
        array(
          'key' => 'field_5c953fd49ef57',
          'label' => 'Address',
          'name' => 'address',
          'type' => 'textarea',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => 4,
          'new_lines' => 'br',
        ),
        array(
          'key' => 'field_5c953fe99ef58',
          'label' => 'Phone',
          'name' => 'phone',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5c953fff9ef59',
          'label' => 'Fax',
          'name' => 'fax',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5c953fff9ef22',
          'label' => 'Email',
          'name' => 'email',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5c9540109ef5a',
          'label' => 'Copyright',
          'name' => 'copyright',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'options_page',
            'operator' => '==',
            'value' => 'acf-options',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5cd44dac63578',
      'title' => 'Staff Details',
      'fields' => array(
        array(
          'key' => 'field_5cd44dd099191',
          'label' => 'Job Titles',
          'name' => 'staff_job_titles',
          'type' => 'repeater',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'table',
          'button_label' => 'Add a Job Title',
          'sub_fields' => array(
            array(
              'key' => 'field_5cd44e82fd6d5',
              'label' => 'Job Title',
              'name' => 'staff_job_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
          ),
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'options_page',
            'operator' => '==',
            'value' => 'acf-options',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5ce3438132e73',
      'title' => 'Social Media',
      'fields' => array(
        array(
          'key' => 'field_5ce34402d4dab',
          'label' => 'Social Media',
          'name' => 'social_media',
          'type' => 'repeater',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'table',
          'button_label' => '',
          'sub_fields' => array(
            array(
              'key' => 'field_5ce34426d4dac',
              'label' => 'Social Channel',
              'name' => 'social_channel',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'twitter' => 'Twitter',
                'linkedin' => 'LinkedIn',
                'instagram' => 'Instagram',
                'facebook' => 'Facebook',
                'youtube' => 'YouTube',
              ),
              'default_value' => array(),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'return_format' => 'value',
              'ajax' => 0,
              'placeholder' => '',
            ),
            array(
              'key' => 'field_5ce34444d4dad',
              'label' => 'Social URL',
              'name' => 'social_url',
              'type' => 'url',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
          ),
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'options_page',
            'operator' => '==',
            'value' => 'acf-options',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5d17d7b1829b6',
      'title' => 'Header Style',
      'fields' => array(
        array(
          'key' => 'field_5d17d7f1eb04a',
          'label' => 'Light or Dark?',
          'name' => 'light_or_dark_header',
          'type' => 'select',
          'instructions' => 'Select light for darkly colored backgrounds, and dark for lightly colored backgrounds',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'light' => 'Light Header',
            'dark' => 'Dark Header',
          ),
          'default_value' => array(
            0 => 'dark',
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'return_format' => 'value',
          'ajax' => 0,
          'placeholder' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'page',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5c954a9073a65',
      'title' => 'Page Hero',
      'fields' => array(
        array(
          'key' => 'field_5c954a9886085',
          'label' => 'Type',
          'name' => 'hero_type',
          'type' => 'select',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'none' => 'None',
            'image' => 'Image',
            'image_slideshow' => 'Image Slideshow',
            'video' => 'Video',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'default_value' => 'image',
          'layout' => 'horizontal',
          'return_format' => 'value',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_5c954ac486086',
          'label' => 'Image',
          'name' => 'hero_image',
          'type' => 'image',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c954a9886085',
                'operator' => '==',
                'value' => 'image',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'url',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array(
          'key' => 'field_5c954ae486087',
          'label' => 'Image Slideshow',
          'name' => 'hero_image_slideshow',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c954a9886085',
                'operator' => '==',
                'value' => 'image_slideshow',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array(
            0 => 'torque_slideshow',
          ),
          'taxonomy' => array(),
          'allow_null' => 0,
          'multiple' => 0,
          'return_format' => 'id',
          'ui' => 1,
        ),
        array(
          'key' => 'field_5c954e7f5e0fc',
          'label' => 'Video Src',
          'name' => 'hero_video_src',
          'type' => 'file',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c954a9886085',
                'operator' => '==',
                'value' => 'video',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'return_format' => 'url',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_3c568c452lak',
          'label' => 'Positioning',
          'name' => 'hero_positioning',
          'type' => 'select',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c954a9886085',
                'operator' => '!=',
                'value' => 'none',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'top' => 'Top of the viewport',
            'after' => 'After the header bar',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'default_value' => 'top',
          'layout' => 'horizontal',
          'return_format' => 'value',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_3cnnad2k29d2lak',
          'label' => 'Hero Height',
          'name' => 'hero_height',
          'type' => 'select',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c954a9886085',
                'operator' => '!=',
                'value' => 'none',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'full' => 'Full-height',
            'half' => 'Half-height',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'default_value' => 'full',
          'layout' => 'horizontal',
          'return_format' => 'value',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_5c568c9903dfjx',
          'label' => 'Text Alignment',
          'name' => 'hero_alignment',
          'type' => 'select',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c954a9886085',
                'operator' => '!=',
                'value' => 'none',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'none' => 'None',
            'left' => 'Left Aligned',
            'center' => 'Center Aligned',
            'right' => 'Right Aligned',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'default_value' => 'none',
          'layout' => 'horizontal',
          'return_format' => 'value',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_5c954bb12e42b',
          'label' => 'Overlay Title',
          'name' => 'hero_overlay_title',
          'type' => 'text',
          'instructions' => 'use em tags to emphasise certain words',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c954a9886085',
                'operator' => '!=',
                'value' => 'none',
              ),
              array(
                'field' => 'field_5c568c9903dfjx',
                'operator' => '!=',
                'value' => 'none',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => 'eg <em>Emphasised text</em> in title',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5c954be22e42c',
          'label' => 'Overlay Subtitle',
          'name' => 'hero_overlay_subtitle',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c954a9886085',
                'operator' => '!=',
                'value' => 'none',
              ),
              array(
                'field' => 'field_5c568c9903dfjx',
                'operator' => '!=',
                'value' => 'none',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'page',
          ),
          array(
            'param' => 'post_template',
            'operator' => '==',
            'value' => 'default',
          ),
        ),
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'page',
          ),
          array(
            'param' => 'post_template',
            'operator' => '==',
            'value' => 'contact.php',
          ),
        ),
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'page',
          ),
          array(
            'param' => 'post_template',
            'operator' => '==',
            'value' => 'careers.php',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5c955c2570f80',
      'title' => 'Page Intro',
      'fields' => array(
        array(
          'key' => 'field_5c955c931df7b',
          'label' => 'Text Alignment',
          'name' => 'page_intro_alignment',
          'type' => 'select',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'none' => 'None',
            'left' => 'Left Aligned',
            'center' => 'Center Aligned',
            'right' => 'Right Aligned',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'default_value' => 'center',
          'layout' => 'horizontal',
          'return_format' => 'value',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_5c945c456df9e',
          'label' => 'Color Combination (Background/Text)',
          'name' => 'page_intro_color',
          'type' => 'select',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'color1' => 'Blue-gray/White',
            'color2' => 'Blue-gray/Medium Green',
            'color3' => 'Blue-gray/Light Green',
            'color4' => 'Medium Green/White',
            'color5' => 'Medium Green/Blue-gray',
            'color6' => 'Medium Green/Light Green',
            'color7' => 'Light Green/White',
            'color8' => 'Light Green/Blue-gray',
            'color9' => 'Light Green/Medium Green',
            'color10' => 'White/Blue-gray',
            'color11' => 'White/Medium Green',
            'color12' => 'White/Light Green',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'default_value' => 'color4',
          'layout' => 'horizontal',
          'return_format' => 'value',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_5c955c421df79',
          'label' => 'Heading',
          'name' => 'page_heading',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c955c931df7b',
                'operator' => '!=',
                'value' => 'none',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5c955c581df7a',
          'label' => 'Intro',
          'name' => 'page_intro',
          'type' => 'textarea',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5c955c931df7b',
                'operator' => '!=',
                'value' => 'none',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => 4,
          'new_lines' => 'br',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'page',
          ),
          array(
            'param' => 'post_template',
            'operator' => '==',
            'value' => 'default',
          ),
          array(
            'param' => 'post_template',
            'operator' => '==',
            'value' => 'careers.php',
          ),
          array(
            'param' => 'post_template',
            'operator' => '!=',
            'value' => 'contact.php',
          ),
        ),
      ),
      'menu_order' => 2,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5c9519163d799',
      'title' => 'Modules',
      'fields' => array(
        array(
          'key' => 'field_5c951924e250c',
          'label' => 'Modules',
          'name' => 'modules',
          'type' => 'flexible_content',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'layouts' => array(
            '5c9561c747434' => array(
              'key' => '5c9561c747434',
              'name' => 'content_section_one',
              'label' => 'Content Section (Image & Text)',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5c9563c44bc13',
                  'label' => 'Align Text',
                  'name' => 'align',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'left' => 'Left',
                    'right' => 'Right',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => 'left',
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5c9561e91af35',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array(
                  'key' => 'field_5c95621c1af36',
                  'label' => 'Heading',
                  'name' => 'heading',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5c9562761af37',
                  'label' => 'Content',
                  'name' => 'content',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 5,
                  'new_lines' => 'br',
                ),
                array(
                  'key' => 'field_5c9562871af38',
                  'label' => 'CTA',
                  'name' => 'cta',
                  'type' => 'link',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                ),
                array(
                  'key' => 'field_5d239831fd912',
                  'label' => 'Top/Bottom Padding?',
                  'name' => 'top_bottom_padding',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'yes' => 'Yes',
                    'no' => 'No',
                  ),
                  'default_value' => array(
                    0 => 'yes',
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'return_format' => 'value',
                  'ajax' => 0,
                  'placeholder' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5d1ce56d29a77' => array(
              'key' => 'layout_5d1ce56d29a77',
              'name' => 'content_section_two',
              'label' => 'Content Section (Heading & Text)',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5d1ce5bc29a78',
                  'label' => 'Align Text',
                  'name' => 'align',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'left' => 'Left Aligned',
                    'center' => 'Center Aligned',
                    'right' => 'Right Aligned',
                  ),
                  'default_value' => array(
                    0 => 'center',
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'return_format' => 'value',
                  'ajax' => 0,
                  'placeholder' => '',
                ),
                array(
                  'key' => 'field_5d1ce5f229a79',
                  'label' => 'Color Combination (Background/Text)',
                  'name' => 'color_combo',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'color1' => 'Blue-gray/White',
                    'color2' => 'Blue-gray/Medium Green',
                    'color3' => 'Blue-gray/Light Green',
                    'color4' => 'Medium Green/White',
                    'color5' => 'Medium Green/Blue-gray',
                    'color6' => 'Medium Green/Light Green',
                    'color7' => 'Light Green/White',
                    'color8' => 'Light Green/Blue-gray',
                    'color9' => 'Light Green/Medium Green',
                    'color10' => 'White/Blue-gray',
                    'color11' => 'White/Medium Green',
                    'color12' => 'White/Light Green',
                  ),
                  'default_value' => array(
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'return_format' => 'value',
                  'ajax' => 0,
                  'placeholder' => '',
                ),
                array(
                  'key' => 'field_5d1ce74c29a7a',
                  'label' => 'Heading',
                  'name' => 'heading',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5d1ce76029a7b',
                  'label' => 'Content',
                  'name' => 'content',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
                ),
                array(
                  'key' => 'field_5d1ce523jkb29a78',
                  'label' => 'Bottom Padding?',
                  'name' => 'bottom_padding',
                  'type' => 'select',
                  'instructions' => 'Yes: identical bottom-padding to Page Intro section. No: minimal bottom-padding, for use in conjunction with introducing another Module for instance.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'yes' => 'Yes',
                    'no' => 'No',
                  ),
                  'default_value' => array(
                    0 => 'yes',
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'return_format' => 'value',
                  'ajax' => 0,
                  'placeholder' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5c99241c74csl36' => array(
              'key' => 'layout_5c99241c74csl36',
              'name' => 'content_section_three',
              'label' => 'Content Section (Image, Quote & Full-width CTA)',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_xo23jf349csd',
                  'label' => 'Align Text',
                  'name' => 'align',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'left' => 'Left',
                    'right' => 'Right',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => 'left',
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_xo23jfk8nb76d',
                  'label' => 'Background Color',
                  'name' => 'background_color',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'white' => 'White',
                    'green' => 'Green',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => array(
                    0 => 'white',
                  ),
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'ajax' => 0,
                  'placeholder' => '',
                ),
                array(
                  'key' => 'field_mmj2d20disfc',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array(
                  'key' => 'field_5kjh23xsaf',
                  'label' => 'Quote',
                  'name' => 'quote',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_1lksc76029a7b',
                  'label' => 'Content',
                  'name' => 'content',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
                ),
                array(
                  'key' => 'field_5c2dsihbbqw',
                  'label' => 'CTA',
                  'name' => 'cta',
                  'type' => 'link',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5c956991bcc4b' => array(
              'key' => 'layout_5c956991bcc4b',
              'name' => 'cta_section',
              'label' => 'CTA Section',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5c956991bcc4c',
                  'label' => 'Heading',
                  'name' => 'heading',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5c956991bcc4d',
                  'label' => 'Content',
                  'name' => 'content',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 5,
                  'new_lines' => 'br',
                ),
                array(
                  'key' => 'field_5c956991bcc4e',
                  'label' => 'CTA',
                  'name' => 'cta',
                  'type' => 'link',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                ),
                array(
                  'key' => 'field_5d239c82b5ee1',
                  'label' => 'Align Background Graphic',
                  'name' => 'align_background_graphic',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'left' => 'Left',
                    'right' => 'Right',
                  ),
                  'default_value' => array(
                    0 => 'right',
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'return_format' => 'value',
                  'ajax' => 0,
                  'placeholder' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5d238fd521011' => array(
              'key' => 'layout_5d238fd521011',
              'name' => 'image_gallery',
              'label' => 'Image Gallery',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5d238fdd21012',
                  'label' => 'Images',
                  'name' => 'images',
                  'type' => 'gallery',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'min' => 1,
                  'max' => 20,
                  'insert' => 'append',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5d2393bd98f24' => array(
              'key' => 'layout_5d2393bd98f24',
              'name' => 'video',
              'label' => 'Video',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5d23940098f25',
                  'label' => 'Video',
                  'name' => 'video_src',
                  'type' => 'file',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'url',
                  'library' => 'all',
                  'min_size' => '',
                  'max_size' => 50,
                  'mime_types' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5c95192ad0ff0' => array(
              'key' => '5c95192ad0ff0',
              'name' => 'post_slideshow',
              'label' => 'Post Slideshow',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5c951939e250d',
                  'label' => 'Slideshow',
                  'name' => 'slideshow_id',
                  'type' => 'post_object',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'post_type' => array(
                    0 => 'torque_post_ss',
                  ),
                  'taxonomy' => array(
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'return_format' => 'id',
                  'ui' => 1,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '5c9d3f4702dde' => array(
              'key' => '5c9d3f4702dde',
              'name' => 'staff_members',
              'label' => 'Staff Members',
              'display' => 'block',
              'sub_fields' => array(
              ),
              'min' => '',
              'max' => '',
            ),
            '5c9d3f4702arg' => array(
              'key' => '5c9d3f4702arg',
              'name' => 'mailchimp_form',
              'label' => 'MailChimp Form',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5c951939e2222',
                  'label' => 'Title',
                  'name' => 'mailchimp_title',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'post_type' => array(
                  ),
                  'taxonomy' => array(
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'return_format' => '',
                  'ui' => 1,
                  'default_value' => '',
                  'maxlength' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                ),
                array(
                  'key' => 'field_5c951939e2332',
                  'label' => 'description',
                  'name' => 'mailchimp_desc',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'post_type' => array(
                  ),
                  'taxonomy' => array(
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'return_format' => '',
                  'ui' => 1,
                  'default_value' => '',
                  'new_lines' => '',
                  'maxlength' => '',
                  'placeholder' => '',
                  'rows' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
          ),
          'button_label' => 'Add Module',
          'min' => '',
          'max' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'page',
          ),
          array(
            'param' => 'post_template',
            'operator' => '==',
            'value' => 'default',
          ),
          array(
            'param' => 'post_template',
            'operator' => '!=',
            'value' => 'careers.php',
          ),
          array(
            'param' => 'post_template',
            'operator' => '!=',
            'value' => 'contact.php',
          ),
        ),
      ),
      'menu_order' => 10,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5d23b5d75e7ee',
      'title' => 'Careers Modules',
      'fields' => array(
        array(
          'key' => 'field_5d23bcb87dccc',
          'label' => 'Career Modules',
          'name' => 'career_modules',
          'type' => 'flexible_content',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'layouts' => array(
            '5c9561c74csdc34' => array(
              'key' => '5c9561c74csdc34',
              'name' => 'content_section_one',
              'label' => 'Content Section (Image & Text)',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5c9563c44bzz2',
                  'label' => 'Align Text',
                  'name' => 'align',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'left' => 'Left',
                    'right' => 'Right',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => 'left',
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5c95m29e91af35',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array(
                  'key' => 'field_5c23b7c1af36',
                  'label' => 'Heading',
                  'name' => 'heading',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array(
                  'key' => 'field_5c95627v4af37',
                  'label' => 'Content',
                  'name' => 'content',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 5,
                  'new_lines' => 'br',
                ),
                array(
                  'key' => 'field_5c956282xcr4',
                  'label' => 'CTA',
                  'name' => 'cta',
                  'type' => 'link',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                ),
                array(
                  'key' => 'field_5db4xsc15512',
                  'label' => 'Top/Bottom Padding?',
                  'name' => 'top_bottom_padding',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'yes' => 'Yes',
                    'no' => 'No',
                  ),
                  'default_value' => array(
                    0 => 'yes',
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'return_format' => 'value',
                  'ajax' => 0,
                  'placeholder' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5d23c62e9f0d4' => array(
              'key' => 'layout_5d23c62e9f0d4',
              'name' => 'list_careers_simple',
              'label' => 'List Careers (simple)',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5d23c643vswd5',
                  'label' => 'Number of Careers',
                  'name' => 'number_of_careers',
                  'type' => 'select',
                  'instructions' => 'How many careers to show initially, and upon every click of \'load more\'.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    '999' => 'All',
                    '1' => '1',
                    '2' => '2',
                    '3' => '3',
                    '4' => '4',
                    '5' => '5',
                    '6' => '6',
                    '7' => '7',
                    '8' => '8',
                    '9' => '9',
                    '10' => '10',
                  ),
                  'default_value' => array(
                    0 => '999',
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 0,
                  'return_format' => 'value',
                  'ajax' => 0,
                  'placeholder' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5d23c6b79f0d6' => array(
              'key' => 'layout_5d23c6b79f0d6',
              'name' => 'careers_form',
              'label' => 'Careers Form',
              'display' => 'block',
              'sub_fields' => array(
              ),
              'min' => '',
              'max' => '',
            ),
          ),
          'button_label' => 'Add Careers Module',
          'min' => '',
          'max' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'page_template',
            'operator' => '==',
            'value' => 'careers.php',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));
	  
		// Add the ACF fields to the Careers CPT
		acf_add_local_field_group(array(
			'key' => 'group_5d02766fe2b64',
			'title' => 'Career Form Settings',
			'fields' => array(
				array(
					'key' => 'field_5d0276901e091',
					'label' => 'Notification Email',
					'name' => 'notification_email',
					'type' => 'email',
					'instructions' => 'Please enter the email address for which you\'d like to receive notifications of Career submissions.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_template',
						'operator' => '==',
						'value' => 'careers.php',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'side',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		));

    acf_add_local_field_group(array(
      'key' => 'group_5di2hdxbd75e7ee',
      'title' => 'Contact Modules',
      'fields' => array(
        array(
          'key' => 'field_5c95378kasdf7a',
          'label' => 'Intro',
          'name' => 'page_intro',
          'type' => 'textarea',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => 4,
          'new_lines' => 'br',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'page_template',
            'operator' => '==',
            'value' => 'contact.php',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));

  }
}
